[package]
name = "typus_oracle"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
SupraOracle = { local = "./price-oracle-framework" }

[addresses]
typus_oracle =  "0x0870508caaa0859321f3f5c8335243bd79356230"
sui =  "0000000000000000000000000000000000000002"
