[package]
name = 'SupraOracle'
version = '1.0.0'

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }

[addresses]
SupraOracle = "0x36ff3c9e8d238bd1cf9091382c2321e116480698"